#!/usr/bin/env bash
#Prints best school with a condition on the 9th Prints

count=1
while [ $count -le 10 ]
do
    echo "Best school"
    if [ $count -eq 8 ]
    then
        echo "Hi"
        fi
        ((count++))
done